<?php 
Class CetQstprodConstTextes 
{
  const bouchon = "BOUCHON";
  const informatif_sondage = "Enquête auprès des producteurs : Ce questionnaire vise à prendre la mesure des freins et difficultés rencontrés par les producteurs. Vos réponses seront gérées de manière anonyme et ne seront pas divulguées dans la version consultable de l’annuaire.";
  const login_intro_block_textinf_a = "Castillonnais En Transition porte un projet de développement des Circuits Alimentaires Locaux de produits bio ou y tendant sur notre territoire. Il s'agit de mettre à disposition des consommateurs un annuaire en ligne apportant une information claire et à jour sur comment se procurer ces productions alimentaires. Le but de cet annuaire est de favoriser le rapprochement entre les consommateurs et les producteurs pour remettre l'alimentation et l'agriculture à leur juste place dans nos vies, dans le respect de notre environnement."; 
  const login_intro_block_textinf_b = "Notre projet a également l'ambition, dans un deuxième temps, de favoriser la solidarité et d'envisager la résilience alimentaire de notre territoire."; 
  const login_intro_block_textinf_c = "Cet annuaire sera diffusé localement auprès de toutes les structures qui sont en lien avec le public : les mairies, les communautés de communes, offices de tourisme, associations locales, marchés..., en version papier.";  
  const login_intro_block_textinf_d = "Ce projet est financé par la Région Nouvelle-Aquitaine et l'Union Européenne.";
  const login_intro_block_textinf_e = "Si vous êtes producteur et vous souhaitez vous inscrire pour être référencé dans l'annuaire, <b>cliquez ci-dessous</b> :";
  const login_intro_block_textinf_f = "Le questionnaire du projet Circuits Alimentaires Locaux comporte 3 dimensions :<br><ul><li>1 l'annuaire</li><li>2 la solidarité pour développer un forum</li><li>3 la résilience  pour lancer des actions spécifiques</li></ul>";
  
  const recap_questionnaire_declaratif_a = "Acceptation d'utilisation des données Les informations portées sur ce formulaire sont facultatives. Elles font l’objet d’un traitement informatisé destiné à répertorier dans un document et sur une carte toutes les personnes ayant un commerce ou une activité de première nécessité. Les destinataires des données sont : Castillonnais en transition. Depuis la loi “informatique et libertés” du 6 janvier 1978 modifiée, vous bénéficiez d’un droit d’accès et de rectification aux informations qui vous concernent. Si vous souhaitez exercer ce droit et obtenir communication des informations vous concernant, veuillez vous adresser à contact@castillonnaisentransition.org. Vous pouvez également, pour des motifs légitimes, vous opposer au traitement des données vous concernant. Acceptez-vous de nous transmettre vos données pour la création de cette carte et ce document consultable par tous ?";

  const nouveau_monde_titre = "ENSEMBLE CONSTRUISONS LE NOUVEAU MONDE !";
  const nouveau_monde_p1 = "Avec un projet d'accompagnement des habitants du territoire vers la transition ecologique, notamment autour de l'alimentation bio, l'association Castillonnais en transition (150 adhérents) a mis en place depuis 2 ans un tiers-lieu « de-ci de-là ». L'association dispose d'un local à Castillon la Bataille en Gironde, qui abrite une épicerie bio participative qui propose les produits d'une vingtaine de producteurs bio locaux girondins, périgourdins et lot-et-garonnais, ainsi qu'un café associatif. Elle dispose d'un second local à Saint Michel de Montaigne en Dordogne, un atelier de réparation agricole devenu espace de travail et de formation partagés. Castillonnais en transition a aussi une activité de « recherche-action » autour du renforcement de l'autonomie alimentaire en bio du territoire.";
  const nouveau_monde_p2 = "Dans le cadre de cette dernière activité, nous avons été retenu par la Région Nouvelle Aquitaine pour mettre en place un projet de développement de « circuits alimentaires locaux ». Il comprend le recensement des producteurs bio dans un rayon de 40 km autour de Castillon avec la réalisation d'un annuaire via une plateforme numérique.";
  const nouveau_monde_p3 = "Afin d'avoir une vraie plus-value par rapport aux plateformes existantes, nous souhaitons via ce questionnaire vous référencer et connaître vos besoins et vos attentes par rapport à ce type d'outil. Cela dans un moment particulier de crise sanitaire et économique, mais aussi d'une profonde volonté collective de renforcement de la résilience et de l'autonomie de nos territoires via une relocalisation de la production, la transformation et la commercialisation de notre alimentation.";

  const notre_projet_titre = "Voici notre projet de circuits alimentaires locaux DECIDELABIOLOCALE.ORG";
  const notre_projet_debut = "L'association Castillonnais en transition est composée de girondins et périgourdins engagés. Elle travaille au développement de la BIO Locale. Nos priorités sont de :";
  const notre_projet_priorite_1 = "Remettre l'agriculture, l'alimentation, le vivant, à une place centrale.";
  const notre_projet_priorite_2 = "Renforcer la résilience alimentaire de nos territoires.";
  const notre_projet_priorite_3 = "Créer du lien, de la solidarité et de l'entraide entre producteurs, entre producteurs et consommateurs, avec les collectivités locales engagées, les associations, les chercheurs...";
  const notre_projet_priorite_4 = "A partir de ces priorités nous travaillons sur un projet de plate forme numérique financée par le Conseil régional de Nouvelle Aquitaine et l'Europe. Elle a un double objectif :";
  const notre_projet_priorite_4_a = "être exhaustive, en présentant gratuitement tout les producteurs BIO et y tendant qui le souhaitent, dans un rayon de 40 km autour de Castillon la Bataille.<br><a href=\"./?statut=bio.ytendant&anr=true\" target=\"black_\">En savoir plus</a> sur le BIO et les producteur.e.s y tendant.";
  const notre_projet_priorite_4_b = "être construite à partir de vos besoins et attentes. Le questionnaire ci-dessous va nous permettre de recueillir ces informations qui nous permettront de valoriser votre ferme, votre travail et de connaître vos attentes.";
}